<?php if ($this->isEnabled()): ?>
<div class="fieldset">
    <h2 class="legend"><?php echo $this->__('Shop and Ship') ?></h2>
    <form action="<?php echo $this->getAddressUrl() ?>" method="post" id="sns-form" autocomplete="off">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="sns-email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                    <div class="input-box">
                        <input type="text" name="sns-email" value="" title="<?php echo $this->__('Email') ?>" class="input-text required-entry validate-email" id="sns-email" />
                    </div>
                </div>
                <div class="field">
                    <label for="sns-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" name="sns-password" id="sns-password" title="<?php echo $this->__('Password') ?>" value="" class="input-text required-entry" />
                    </div>
                </div>
            </li>
            <li class="wide">
                <button type="submit" title="<?php echo $this->__('Get Addresses List') ?>" class="button"><span><span><?php echo $this->__('Get Addresses List') ?></span></span></button>
                <span id="sns-get-addresses-loader">&nbsp;<img src="<?php echo $this->getSkinUrl('shopgo/sns/image/ajax-loader.gif') ?>" alt="Loading..." /></span>
            </li>
            <li id="sns-addresses-container" class="wide">
                <label for="sns-addresses"><?php echo $this->__('Shop and Ship Addresses') ?>&nbsp;<span class="showhide">(<a href="#"><?php echo $this->__('hide') ?></a>)</span></label>
                <div class="clearer"></div>
                <div id="sns-addresses-list"></div>
            </li>
        </ul>
    </form>
</div>
<script type="text/javascript">//<![CDATA[
    if (typeof shopgoSns == 'undefined') {
        var shopgoSns = new Object();
    }

    shopgoSns.form = new VarienForm('sns-form', true);
    shopgoSns.addressesRegions = eval("(" + '<?php echo $this->getAddressesRegions() ?>' + ")");
    shopgoSns.missingAddressRegions  = eval("(" + '<?php echo $this->getMissingAddressRegions() ?>' + ")");
//]]></script>
<?php endif ?>
